[package]
name = "xc3-sound-replace"
version = "1.0.0"
authors = ["RoccoDev <hey@rocco.dev>"]
edition = "2021"
license = "gpl-3.0"

[package.metadata.skyline]
titleid = "010074F013262000" # Xenoblade Chronicles 3
package-resources = [
    { local = "res/empty-file", package = "/atmosphere/contents/010074F013262000/romfs/sound/.put-files-here" }
]
custom-npdm = "res/npdm/xc3.npdm"

[lib]
crate-type = ["cdylib"]

[dependencies]
skyline = { git = "https://github.com/ultimate-research/skyline-rs.git" }
fnv = "1.0.3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
